---
- include_role:
    name: openio-service
  vars:
    openio_service_type: "filebeat"
    openio_service_namespace: "{{ openio_filebeat_namespace }}"
    openio_service_maintenance_mode: "{{ openio_filebeat_maintenance_mode }}"
    openio_service_packages:
      - oio-filebeat
    openio_service_directories:
      - path: "{{ openio_service_volume }}"
    openio_service_configuration_files:
      - name: filebeat.yml
    openio_service_services:
      - command: >-
          /usr/share/oio-filebeat/bin/filebeat
          -c {{ openio_service_conf_dir }}/filebeat.yml
          -path.home /usr/share/oio-filebeat
          -path.data {{ openio_service_volume }}

    openio_service_checks:
      - shell:
          cmd: "pgrep filebeat"
        retries: 30
        delay: 2
...
