---
- name: Install Key
  rpm_key:
    key: "{{ openio_filebeat_gpg_url }}"
  tags: install

- name: Add repo
  yum_repository:
    name: filebeat
    description: Elastic filebeat Repository
    baseurl: "{{ openio_filebeat_repo_url }}"
    enabled: true
    gpgcheck: true
    gpgkey: "{{ openio_filebeat_gpg_url }}"
  tags: install

- name: Install filebeat
  yum:
    name: "filebeat-{{ openio_filebeat_version }}"
    state: present
  tags: install
...
